name: GitHub Classroom Workflow

#on: workflow_dispatch

on: 
  push:
    paths-ignore:
      - '.github/*'

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  Checking-Solution:
    runs-on: gtest
    timeout-minutes: 10
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
             make
             ./test
      - name: Autograding
        uses: amcp-pit/autograding@v1
      - name: Memory leaks
        run: |
             valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./boolcalc -isfull tests/funs06.in output.txt
      - name: Code linting
        uses: amcp-pit/cpp-linter@v1
        with:
          extra-args-before: '-xc++'
          after-args: '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
      - name: Checkout
        uses: actions/checkout@v3
      - name: CPD
        uses: amcp-pit/cpd-action@v1
        id: cpd
        with:
          repository: ${{ github.repository }}
          collection: ${{ github.repository_owner  }}
      - name: Clean
        run: |
             rm -rf ./* || true
             rm -rf ./.??* || true
